- search:
    provider: duckduckgo
    target: _blank

- resources:
    cpu: true
    memory: true
    disk: /
    label: "Oracle VPS"

# - glances:
#     label: "DataManager"
#     url: "http://100.x.y.z:61208"
#     version: 4
#     cpu: true
#     mem: true
#     expanded: true
#     disk:
#       - /
